sc:
  image: semcon/sc-base
  env_file: .env
  environment:
    RAILS_ENV: production
  links:
    - db
  ports:
    - "3000:3000"

db:
  image: postgres:12.1
  volumes:
    - sc-postgres:/var/lib/postgresql/data
